name: Generate Snake Animation

on:
  schedule:
    # Executa a cada 6 horas
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Baixar reposit√≥rio
      - uses: actions/checkout@v2
      # Configurar a cobra
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: AlexPablo-hub
          outputs: gif
      - uses: actions/upload-artifact@v2
        with:
          name: snake-gif
          path: dist/github-contribution-grid-snake.svg
      - name: Deploy Snake Animation
        run: git push
